version: '3.7'

services:

  local_db:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      - "MYSQL_DATABASE=survey_bot_db"
      - "MYSQL_ROOT_PASSWORD=password"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
    mysql_data:

